export const feelingEmotions: any = {
  down: [
    'sadness',
    'depressed',
    'despair',
    'angry',
    'resigned',
    'grief',
    'miserable',
    'unwanted',
    'frustration',
    'guilt',
    'hopeless',
    'sorrow',
  ],
  low: [
    'dismal',
    'unhappy',
    'defeated',
    'agitated',
    'stressed',
    'lethargic',
    'withdrawn',
    'tense',
    'anxious',
    'isolated',
  ],
  neutral: [
    'bored',
    'calm',
    'meh',
    'tempered',
    'undisturbed',
    'observant',
    'detached',
    'alert',
    'focused',
  ],
  fine: [
    'optimistic',
    'grateful',
    'satisfied',
    'amused',
    'pleased',
    'comfortable',
    'content',
    'serene',
    'chill',
    'mellow',
    'eager',
    'included',
  ],
  good: [
    'ecstatic',
    'thrilled',
    'tranquil',
    'accepted',
    'satisfied',
    'valued',
    'inspired',
    'empowered',
    'joyful',
    'happy',
    'loved',
    'vibrant',
  ],
};
